'use client';
import axios from 'axios';
import Providers from '@/src/redux/provider';
import { SessionProvider } from 'next-auth/react';
import { Navbar, Header, Playbar } from '@/components';
import './globals.css';

export const metadata = {
	title: 'Mixtape',
	description: 'Generated by create next app',
};

interface IProps {
	children: React.ReactNode;
	session: any;
}

axios.defaults.baseURL = 'http://localhost:4000/';
// axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
// axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

export default function RootLayout({ children, session }: IProps) {
	return (
		<html lang="en">
			<Providers>
				<body>
					<SessionProvider session={session}>
						<Header />
						<div className="relative">
							<Navbar />
							<main className="active">{children}</main>
						</div>
						<Playbar />
					</SessionProvider>
				</body>
			</Providers>
		</html>
	);
}
