'use client';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import './globals.css';
import { Quicksand } from 'next/font/google';
import Providers from '@/src/redux/provider';
import Playbar from '@/components/Playbar';
import "../../mixtape-app/styles/index.css";
import "../../mixtape-app/styles/customize-progress-bar.css";
import { SessionProvider } from 'next-auth/react';

const quicksand = Quicksand({ subsets: ['latin', 'vietnamese'] });

export const metadata = {
    title: 'Mixtape',
    description: 'Generated by create next app',
};

interface IProps {
    children: React.ReactNode;
    session: any;
}

export default function RootLayout({ children, session }: IProps) {
    return (
        <html lang="en">
            <Providers>
                <body className={quicksand.className}>
                    <SessionProvider session={session}>
                        <Header />
                        <div className="relative">
                            <Navbar />
                            <main className="active">
                                {children}
                            </main>
                        </div>
                        <Playbar />
                    </SessionProvider>
                </body>
            </Providers>
        </html>
    );
}
