import Navbar from "@/components/Navbar";
// import Footer from '@/components/Footer'
import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/src/redux/provider";
import Playbar from "@/components/Playbar";
import "../../mixtape-app/styles/index.css";
import "../../mixtape-app/styles/customize-progress-bar.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mixtape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Header />
          <div className="relative">
            <Navbar />
            <main className="active">
              {children}
              {/* <Footer /> */}
            </main>
          </div>
          <Playbar />
        </body>
      </Providers>
    </html>
  );
}
